### ISSUE TITLE
overlaying 3D model on tracked tool

### ISSUE THREAD

**Issue by mrcfschr** [lihaowei1999/IRToolTrackingWithHololens2#1]
Hi!
Thank you very much for sharing this super cool project!
I'm trying to use this code for my research and I followed the readme and tracking the tool works (when the markers are visible transforms are showing up in the python UI).
![image](https://user-images.githubusercontent.com/57159035/225128482-50529d5a-aefb-496d-a8f1-1482f7351a00.png)
However, I'm not entirely sure how to modify the Unity scene to overlay a 3D model relative to the tracked markers. In order to do so I would need the xyz coordinates of the 4 tracked IR spheres in the Unity coordinate system ideally with correspondences but not absolutely necessary.
I noticed that there is a NetworkServer script in the example scene where one can set an ip and there is lots of commented-out code?
Should I set that ip to the IP of my HoloLens?
How do I get the sphere positions?
I'm using windows 10.

**Comment by lihaowei1999** [comment]
Look for branch zmq provided by @petergu684 please.

**Comment by lihaowei1999** [comment]
Look for branch [zmq](https://github.com/lihaowei1999/IRToolTrackingWithHololens2/tree/zmq) provided by @petergu684 please.

**Comment by mrcfschr** [comment]
Ok Thank you, I'll give it a try! I'll leave this open for the time being in case I run into any issues I can document it so maybe it helps others.
