### ISSUE TITLE
Constructing tool from prior knowledge (200 micron accuracy CAD model)

### ISSUE THREAD

**Issue by mrcfschr** [lihaowei1999/IRToolTrackingWithHololens2#2]
I know the exact distance up to 200 microns between my ir tracking spheres and their radius and I was wondering if there is a way to construct the tool from this prior knowledge instead of using the construct tool option and 300 frames of active brightness from AHAT. I imagine using this prior knowledge would be less error-prone? But maybe I'm wrong?
The ir spheres:
![image](https://user-images.githubusercontent.com/57159035/225130419-b535b371-8809-4ed5-a8aa-dd59fb9ce8a7.png)

**Comment by lihaowei1999** [comment]
Sure, if the tool is CNC manufactured, the production provides a high-accuracy definition. You can use the center of the hole for the insertion of the NDI balls in the tool space (you can use drawings if you are using Solidworks to draw the tool to get the center of the sphere). You can manually fill the UI_python/ToolList/xxx.mat and add that to config.json for tracking.

**Comment by mrcfschr** [comment]
Ok Thank you, I'll give it a try! I'll leave this open for the time being in case I run into any issues I can document it so maybe it helps others.
