### ISSUE TITLE
getting and setting the intrinsics

### ISSUE THREAD

**Issue by mrcfschr** [lihaowei1999/IRToolTrackingWithHololens2#3]
I was wondering if you could share in more detail how you got the ir cameras' intrinsics?
The paper explains:
![image](https://user-images.githubusercontent.com/57159035/225131409-0a60d8fc-21cd-4710-a8d4-1c903b0c0aad.png)
However, I'm unsure what to do exactly in practice.
Do you still have the code to run over the dataset/ to move the robotic arm and would be willing to share it?
I was thinking about using this:
https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html
Is the distortion both radial and tangential?
Did you perform a histogram equalization for better corner detection?
If so how did you deal with the IR frames having 16 bits and OpenCV's histogram equalization function only supporting 8 bits? Is it fine to lose that bit of information?
Also, what's the best way to set the intrinsics?
Did you try using research modes project and unproject functions(e.g. MapImagePointToCameraUnitPlane) , if so, how did they compare to custom-calibrated intrinsics?
Thank you so much for your help!
Update:
This is what i got so far: https://drive.google.com/file/d/1rgc01WuRAIh_TM_ut0QdsQyjZ8_14m9z/view?usp=sharing
Wonder if it's good enough for surgical tool tracking

**Comment by lihaowei1999** [comment]
1. robot arm is only used for a steady hold. 
2. The code is the same as any other chessboard calibration provided by opencv, without special processing
3. The frame is 16 bit, but the chessboard only ranges from 200-500, you can divide the intensity by 2 or 3, even the markers are only as high as 2000-3000
4. Research Mode tried. If you are writing tracking on native C++ in Hololens, you should directly use that, the projection function for AHAT is accurate.

**Comment by mrcfschr** [comment]
Thank you, especially 4 is good to know !
