### ISSUE TITLE
Making Tracking Tool file

### ISSUE THREAD

**Issue by kyh0214** [lihaowei1999/IRToolTrackingWithHololens2#4]
Hello, your [IRToolTrackingWithHololens2] is good reference for access to intrinsic Hololens 2 sensor.

However, there are some problems with creating the Tool.mat file 

Describing my steps in the UI(Following your Installing and Running Guide)
1. Clicked connection to Hololens View(Done)
2. Clicked Collect button with modify filename I want(Done)-> get  "filename.npy" file
3. In Tool Def line I modified "OfflineVideoName" to "filename" 
4. Then I clicked ConstructTool Button and got error message like below
  
_File "main.py", line 503, in OnToolConstructionButtonClicked
    DataDefCollected=np.array(xyzs)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (300,) + inhomogeneous part._

So, I want to know about making my own tool and Tracking that tool
1.  Is there a way to create a .mat file through matlab?
2. When I make .npy file using Collect button, my Hololens2 and Infrared marker should be pinned to specific location or not?

Thank you for reading and I look forward to hearing from you soon.

**Comment by lihaowei1999** [comment]
I guess that it is because there is a marker detected unstable, so that the point of markers changes within time.
Yes, you can open the definition the file and change it with Matlab, the format is easy to understand after you load that to Matlab.
In this edition of code, you need to fix the hololens2 and the tool. You can do detection using frame 1 as definition to find the pairing between each frame to make it free when definition.

**Comment by kyh0214** [comment]
I appreciated about your opinion.
Actually I solved this problem at last night with reference to your paper.
But, I got another problem... :(
The problem is that when I clicked "Track" Button(in UI), the process is paused and closed 
So, I can not  see tracking Matrix.
Can I have your sample .mat code and Cache .npy file ?? or recording data?
I want to know how these UI are operating.

Thanks again

**Comment by lihaowei1999** [comment]
You can refer to the mat file in  
[https://github.com/lihaowei1999/IRToolTrackingWithHololens2/blob/main/UI_python/ToolList/ToolName.mat](url).
If you open that in Matlab, you can find Loss, ToolName and ToolShape. The mat file is loaded by code with spicy.io.loadmat, only ToolShape is used. So you can change anything you want in the file, save that to mat file, and run tracking.
I now do not have a cached npy file as I'm now moved to completely c++ for tracking. A similar implementation was made public [https://github.com/andreaskeller96/HoloLens2-IRTracking](url).
